In [1]:
import numpy as np
import pandas as pd
import difflib
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [86]:
dta=pd.read_csv('phrases.csv',encoding='unicode_escape')

In [87]:
dta['Index'] = range(1, len(dta) + 1)

In [90]:
selected_features = ['Phrases']
print(selected_features)

['Phrases']


In [91]:
for feature in selected_features:
  dta[feature] = dta[feature].fillna('')

In [92]:
combined_features = dta['Phrases']

In [93]:
print(combined_features)

0                    how company compares to its peers?
1     what is the detailed income statement breakdow...
2                     world premium penetration in 2020
3     How does the forecasted insurance premium pene...
4     what are the total losses for companies in cou...
5                  Insurance premiums market in Country
6     How have the profit margins been for the airli...
7     What is the complete profile of the top oil rigs?
8                  what is company general information?
9      How is the airline industry performing globally?
10    how does economic profit for in country compar...
11              most profitable insurance company India
12    Give me a detailed breakup of the income and e...
13                Show me all the oil rigs in the world
14    What were the premiums earned by the Indian in...
15    How much have premiums grown as compared to cl...
16    Which are the best performing insurance firms ...
17                What is the ROE of the Indian 

In [94]:
vectorizer = TfidfVectorizer()

In [95]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [96]:
print(feature_vectors)

  (0, 133)	0.4434219219633911
  (0, 95)	0.4434219219633911
  (0, 166)	0.36323941516814995
  (0, 49)	0.4903256816524265
  (0, 46)	0.41014317485718527
  (0, 84)	0.2572439067170238
  (1, 21)	0.3931004592032097
  (1, 126)	0.21521511596637974
  (1, 31)	0.43468137471247725
  (1, 161)	0.43468137471247725
  (1, 87)	0.3931004592032097
  (1, 55)	0.3931004592032097
  (1, 163)	0.144132071398556
  (1, 94)	0.22805074095104927
  (1, 174)	0.19854861189249312
  (2, 0)	0.3840889727551636
  (2, 86)	0.23065797279765857
  (2, 134)	0.5161629460395745
  (2, 140)	0.5161629460395745
  (2, 177)	0.5161629460395745
  (3, 47)	0.3039706660302439
  (3, 170)	0.33612371567846516
  (3, 52)	0.24900466460522586
  (3, 93)	0.2168516149570046
  (3, 74)	0.33612371567846516
  :	:
  (46, 94)	0.2072457554425068
  (46, 166)	0.2926398839286317
  (47, 5)	0.5531699585575293
  (47, 26)	0.5531699585575293
  (47, 16)	0.31933587028602145
  (47, 0)	0.3722512116076045
  (47, 86)	0.223549010597644
  (47, 163)	0.1834206308358339
  (47, 174

In [97]:
similarity = cosine_similarity(feature_vectors)

In [98]:
print(similarity)

[[1.         0.         0.         ... 0.         0.07380451 0.        ]
 [0.         1.         0.         ... 0.07660416 0.09156415 0.07263783]
 [0.         0.         1.         ... 0.19454095 0.19232236 0.18446822]
 ...
 [0.         0.07660416 0.19454095 ... 1.         0.21965437 0.36791626]
 [0.07380451 0.09156415 0.19232236 ... 0.21965437 1.         0.20828135]
 [0.         0.07263783 0.18446822 ... 0.36791626 0.20828135 1.        ]]


In [99]:
inp = input(' Enter input for which  closest phrase needs to be found : ')

 Enter input for which  closest phrase needs to be found : Mergers among airline companies?


In [100]:
list_of_all_titles = dta['Phrases'].tolist()

In [101]:
find_close_match = difflib.get_close_matches(inp, list_of_all_titles)

In [102]:
close_match = find_close_match[0]

In [106]:
index_of_phrase = dta[dta.Phrases == close_match]['Index'].values[0]

In [107]:
print(index_of)

35


In [108]:
similarity_score = list(enumerate(similarity[index_of_phrase]))
print(similarity_score)

[(0, 0.0), (1, 0.02722939253424601), (2, 0.0), (3, 0.02105552509658867), (4, 0.09557889111181134), (5, 0.0), (6, 0.06036982976713376), (7, 0.054416452660766605), (8, 0.0), (9, 0.03326808549046591), (10, 0.0), (11, 0.4573346869936476), (12, 0.019837092922951924), (13, 0.052609924961415255), (14, 0.051723896967971666), (15, 0.0), (16, 0.23524859072650825), (17, 0.06663084430675138), (18, 0.0), (19, 0.056153405309442184), (20, 0.02162089848895459), (21, 0.2463878851013059), (22, 0.13478425908711963), (23, 0.030845642709456524), (24, 0.0), (25, 0.03275793445068948), (26, 0.10021663258718463), (27, 0.24215447969574774), (28, 0.0), (29, 0.6285500260592929), (30, 0.0), (31, 0.025965771283882243), (32, 0.03717808840947124), (33, 0.0), (34, 0.0), (35, 1.0000000000000002), (36, 0.044980296564918976), (37, 0.028100378142659553), (38, 0.031414344752634424), (39, 0.0), (40, 0.03465142302610856), (41, 0.12569799271360688), (42, 0.0), (43, 0.2819493145001968), (44, 0.0), (45, 0.02441908583883064), (4

In [109]:
len(similarity_score)

50

In [110]:
sorted_similar_Phrase = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_Phrase)

[(35, 1.0000000000000002), (29, 0.6285500260592929), (11, 0.4573346869936476), (49, 0.29646325749128477), (43, 0.2819493145001968), (46, 0.2501850826935917), (21, 0.2463878851013059), (27, 0.24215447969574774), (16, 0.23524859072650825), (47, 0.13968448185812293), (22, 0.13478425908711963), (41, 0.12569799271360688), (26, 0.10021663258718463), (4, 0.09557889111181134), (17, 0.06663084430675138), (6, 0.06036982976713376), (19, 0.056153405309442184), (7, 0.054416452660766605), (13, 0.052609924961415255), (14, 0.051723896967971666), (36, 0.044980296564918976), (32, 0.03717808840947124), (40, 0.03465142302610856), (48, 0.0342565998319668), (9, 0.03326808549046591), (25, 0.03275793445068948), (38, 0.031414344752634424), (23, 0.030845642709456524), (37, 0.028100378142659553), (1, 0.02722939253424601), (31, 0.025965771283882243), (45, 0.02441908583883064), (20, 0.02162089848895459), (3, 0.02105552509658867), (12, 0.019837092922951924), (0, 0.0), (2, 0.0), (5, 0.0), (8, 0.0), (10, 0.0), (15, 0

In [114]:
print('Closest Phrases suggested for you : \n')

i = 1

for Phr in sorted_similar_Phrase:
  index = Phr[0]
  title_from_index = dta[dta.index==index]['Phrases'].values[0]
  if (i<30):
    print(i, '.',title_from_index," ",round(sorted_similar_Phrase[i-1][1],7))
    i+=1

Closest Phrases suggested for you : 

1 . Which are the most profitable airports?   1.0
2 . Which are the top airports?   0.62855
3 . most profitable insurance company India   0.4573347
4 . What are the most prominent bankruptcies in 2020?   0.2964633
5 . What are the most prominent legal cases?   0.2819493
6 . Which country in Europe is going to grow the most in 2020?   0.2501851
7 . Which are the main distribution channels in India?   0.2463879
8 . Which are the aircrafts manufactured by Boeing?   0.2421545
9 . Which are the best performing insurance firms in India?   0.2352486
10 . What are the biggest acquisitions in 2020?   0.1396845
11 . What are the risks in the motor insurance segment in India?   0.1347843
12 . Which Lloyd's syndicates owns the maximum number of assets?   0.125698
13 . How many passengers are carried in ?   0.1002166
14 . what are the total losses for companies in country  non life market?   0.0955789
15 . What is the ROE of the Indian market?   0.0666308
16 . 